# Generated by Django 5.2.7 on 2026-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CivilPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=128, verbose_name="Nombre(s)"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="Apellido Paterno"),
                ),
                (
                    "identity_card",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Cédula de Identidad"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Fecha de Nacimiento")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pareja Civil",
                "verbose_name_plural": "Parejas Civiles",
                "db_table": "civil_partners",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
