# Generated by Django 5.2.7 on 2026-01-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("police_personnel", "0004_alter_personnel_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrenatalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("officer", "Funcionario"),
                            ("civil_partner", "Pareja Civil"),
                        ],
                        default="officer",
                        max_length=50,
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(verbose_name="estimated delivery date"),
                ),
                (
                    "current_gestation_week",
                    models.IntegerField(verbose_name="current gestation week"),
                ),
                (
                    "rh_factor",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        verbose_name="rh factor",
                    ),
                ),
                (
                    "control_location",
                    models.CharField(max_length=255, verbose_name="control location"),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="registration date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prenatal_records",
                        to="police_personnel.personnel",
                        verbose_name="personnel",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prenatal_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user created",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prenatal Record",
                "verbose_name_plural": "Prenatal Records",
                "db_table": "prenatal_records",
                "ordering": ["-registration_date"],
            },
        ),
    ]
