# Generated by Django 5.2.7 on 2026-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prenatal_care", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prenatalrecord",
            name="civil_partner_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="civil partner name"
            ),
        ),
    ]
