# Generated by Django 5.2.7 on 2026-01-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("police_personnel", "0004_alter_personnel_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NatalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("officer", "Funcionario"),
                            ("civil_partner", "Pareja Civil"),
                        ],
                        default="officer",
                        max_length=50,
                        verbose_name="relationship type",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="birthdate")),
                (
                    "country",
                    models.CharField(
                        default="BOLIVIA", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("la_paz", "La Paz"),
                            ("cochabamba", "Cochabamba"),
                            ("santa_cruz", "Santa Cruz"),
                            ("oru", "Oruro"),
                            ("potosi", "Potosí"),
                            ("tarija", "Tarija"),
                            ("chuquisaca", "Chuquisaca"),
                            ("beni", "Beni"),
                            ("pando", "Pando"),
                        ],
                        max_length=50,
                        verbose_name="department",
                    ),
                ),
                ("province", models.CharField(max_length=100, verbose_name="province")),
                ("locality", models.CharField(max_length=100, verbose_name="locality")),
                (
                    "nationality",
                    models.CharField(
                        default="BOLIVIANA", max_length=50, verbose_name="nationality"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="registration date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="natal_data_records",
                        to="police_personnel.personnel",
                        verbose_name="personnel",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="natal_data_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user created",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natal Data",
                "verbose_name_plural": "Natal Data Records",
                "db_table": "natal_data",
                "ordering": ["-registration_date"],
            },
        ),
    ]
