# Generated by Django 5.2.7 on 2026-01-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civil_partners", "0001_initial"),
        ("natal_data", "0001_initial"),
        ("police_personnel", "0004_alter_personnel_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="nataldata",
            name="civil_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="natal_data_records",
                to="civil_partners.civilpartner",
                verbose_name="civil partner",
            ),
        ),
        migrations.AddField(
            model_name="nataldata",
            name="civil_partner_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="civil partner name"
            ),
        ),
        migrations.AlterField(
            model_name="nataldata",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="natal_data_records",
                to="police_personnel.personnel",
                verbose_name="personnel",
            ),
        ),
    ]
