# Generated by Django 5.2.7 on 2025-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='region')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date access')),
            ],
            options={
                'verbose_name': 'Access Login',
                'verbose_name_plural': 'Access Logins',
                'db_table': 'access_login',
                'ordering': ['-date'],
            },
        ),
    ]
