export const ROLE_PATHS: Record<string, string[]> = {
  Admin: ["all"],
  Auxiliar: [
    "/",
    "/formavc09",
    "/upload09",
    "/upload/mobile/",
    "/profile",
    "/sick-leave",
    "/alerts",
    "/blank",
  ],
  AuxiliarSIT: [
    "/",
    "/profile",
    "/formavc09",
    "/upload09",
    "/upload/mobile/",
    "/avc09",
    "/personnel",
    "/hospitals",
    "/units",
    "/alerts",
    "/blank",
  ],
  PersonalTS: [
    "/",
    "/profile",
    "/personnel",
    "/prenatal-records",
    "/natal-data",
    "/hospitals",
    "/units",
    "/alerts",
    "/blank",
  ],
  Archivos: [
    "/",
    "/profile",
    "/personnel",
    "/filepersonnel",
    "/hospitals",
    "/units",
    "/alerts",
    "/blank",
  ],
  Invitado: ["/"],
};

export const PUBLIC_PATHS = ["/signin", "/signup", "/error-404", "/blank"];
