# Generated by Django 5.2.7 on 2026-01-22 00:26

import affiliationavc09.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliationavc09", "0006_affiliationavc09_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliationavc09",
            name="user_deleted",
        ),
        migrations.AddField(
            model_name="affiliationavc09",
            name="scanned_document",
            field=models.FileField(
                blank=True,
                help_text="Imagen JPG, PNG o JPEG del documento",
                null=True,
                upload_to=affiliationavc09.models.document_file_path,
                verbose_name="Documento Escaneado",
            ),
        ),
    ]
