# Generated by Django 5.2.7 on 2025-12-08 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilesessiontoken",
            name="token",
        ),
        migrations.AlterField(
            model_name="mobilesessiontoken",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
